# Generated by Django 5.0.1 on 2024-01-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rk', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('d', models.IntegerField()),
                ('l', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('pts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_End_Year', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('notes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PremierLeagueResultsStandings.notes')),
                ('stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PremierLeagueResultsStandings.stats')),
            ],
        ),
    ]
