# Generated by Django 5.0.1 on 2024-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PremierLeagueResultsStandings', '0003_alter_team_notes_alter_team_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='d',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='gd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='gf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='l',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='mp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='pts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='w',
            field=models.IntegerField(null=True),
        ),
    ]
